# QLoRA Fine-Tuning for Multimodal Alignment of Voxtral with GLaDOS Persona

In [1]:
import torch
import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import AutoProcessor, VoxtralForConditionalGeneration, BitsAndBytesConfig
from transformers.trainer_utils import get_last_checkpoint
from peft import LoraConfig, prepare_model_for_kbit_training, get_peft_model
from trl import SFTTrainer, SFTConfig
import os, gc, json, wandb, warnings

warnings.filterwarnings("ignore", category=UserWarning, module="bitsandbytes")
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
os.environ["TOKENIZERS_PARALLELISM"] = "true"
os.environ["WANDB_PROJECT"] = "Voxtral-GLaDOS-Multimodal"
os.environ["WANDB_LOG_MODEL"] = "false"
os.environ["WANDB_NOTEBOOK_NAME"] = "qlora_finetune.ipynb"
wandb.login()
device = "cuda" if torch.cuda.is_available() else "cpu"
model_id = "mistralai/Voxtral-Mini-3B-2507"
compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

processor = AutoProcessor.from_pretrained(model_id)
# Right padding for training
processor.tokenizer.padding_side = "right"
if processor.tokenizer.pad_token is None:
    processor.tokenizer.pad_token = processor.tokenizer.eos_token
    processor.tokenizer.pad_token_id = processor.tokenizer.eos_token_id

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4", # Highly optimized for speed/accuracy
    bnb_4bit_use_double_quant=True, # Saves extra memory at no speed cost
    bnb_4bit_compute_dtype=compute_dtype
)

# model = VoxtralForConditionalGeneration.from_pretrained(
#             model_id,
#             quantization_config=bnb_config,
#             attn_implementation="flash_attention_2",
#             device_map=device
#         )
# print(model)
# del model
# gc.collect()
# torch.cuda.empty_cache()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.
wandb: Currently logged in as: vitolus (vitolus-universit-ca-foscari-venezia) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
def create_datasets(df, commands_list, processor, test_size=0.1):
    train_cmds, eval_cmds = train_test_split(commands_list, test_size=test_size, random_state=42)

    def format_ds(frame):
        messages = []
        for _, row in frame.iterrows():
            path = os.path.join("data/synthesized_train_16k/", row["Audio_File"])
            if os.path.exists(path):
                target = f"{row['Assistant_Payload']}\n\n{row['Target_GLaDOS_Response']}{processor.tokenizer.eos_token}"
                messages.append([
                    {"role": "user", "content": [{"type": "audio", "path": path}]},
                    {"role": "assistant", "content": [{"type": "text", "text": target}]},
                    {"role": "user", "content": [{"type": "text", "text": "DUMMY_STOP"}]}
                ])
        return Dataset.from_dict({"messages": messages})

    df_train = df[df['User_Command'].isin(train_cmds)]
    df_eval = df[df['User_Command'].isin(eval_cmds)]
    print(f"Train rows: {len(df_train)} | Eval rows: {len(df_eval)}")
    return format_ds(df_train).shuffle(seed=42), format_ds(df_eval)

def get_prepared_model(model_id, quantization_config, device, compute_dtype, processor):
    model = VoxtralForConditionalGeneration.from_pretrained(
        model_id,
        quantization_config=quantization_config,
        attn_implementation="flash_attention_2",
        device_map=device,
        dtype=compute_dtype
    )
    # Prepare model for gradient training
    model = prepare_model_for_kbit_training(model)
    # Essential for preventing backward pass crashes with frozen encoders
    model.enable_input_require_grads()
    # # Revert the text embeddings back to bfloat16/float16 to match the Audio Encoder
    # model.get_input_embeddings().to(compute_dtype)
    # # Also ensure the output layer matches
    # if getattr(model, "get_output_embeddings", None) is not None:
    #     model.get_output_embeddings().to(compute_dtype)
    # # It is also good practice to ensure the audio encoder didn't get accidentally cast to float32
    # if hasattr(model, "audio_encoder"):
    #     model.audio_encoder.to(compute_dtype)
    model.config.update({
        "pad_token_id": processor.tokenizer.pad_token_id,
        "eos_token_id": processor.tokenizer.eos_token_id,
        "bos_token_id": processor.tokenizer.bos_token_id
    })
    return model

def make_voxtral_collate_fn(processor, compute_dtype):
    inst_seq = torch.tensor(processor.tokenizer.encode("[/INST]", add_special_tokens=False))
    seq_len = len(inst_seq)

    def collate_fn(batch):
        inputs = processor.apply_chat_template(
            [item["messages"] for item in batch],
            tokenize=True,
            return_dict=True,
            processor_kwargs={"padding": True, "truncation": True, "max_length": 1536, "return_tensors": "pt"}
        )
        labels = inputs["input_ids"].clone()
        inst_device_seq = inst_seq.to(labels.device)
        for i in range(labels.shape[0]):
            # Mask User Input
            matches = (labels[i].unfold(0, seq_len, 1) == inst_device_seq).all(dim=1).nonzero(as_tuple=True)[0]
            if len(matches) > 0:
                labels[i, :matches[0] + seq_len] = -100
            # Mask Dummy Pad Turn
            eos_idx = (labels[i] == processor.tokenizer.eos_token_id).nonzero(as_tuple=True)[0]
            if len(eos_idx) > 0:
                labels[i, eos_idx[0] + 1:] = -100
                inputs["attention_mask"][i, eos_idx[0] + 1:] = 0
                inputs["input_ids"][i, eos_idx[0] + 1:] = processor.tokenizer.pad_token_id
        inputs["labels"] = labels
        for key, tensor in inputs.items():
            if torch.is_floating_point(tensor):
                inputs[key] = tensor.to(compute_dtype)
        return inputs

    return collate_fn

#### Dataset Formatting for Multimodal SFT

In [3]:
df = pd.read_csv("data/combined_multimodal_dataset_train.csv")
unique_commands = df['User_Command'].unique().tolist()
train_dataset, eval_dataset = create_datasets(df, unique_commands, processor)
del df, unique_commands
gc.collect()

Train rows: 36120 | Eval rows: 4176

8

#### Hyperpatameters tuning

In [4]:
sweep_config = {
        'method': 'bayes', # Bayesian optimization (smarter than random search)
        'metric': {'name': 'eval/loss', 'goal': 'minimize'},
        'early_terminate': {
            'type': 'hyperband',
            'min_iter': 3, # Minimum number of iterations to run
            'eta': 2 # Aggressiveness of early stopping (higher = more aggressive). Hyperband will stop poorly performing runs early based on intermediate results, allowing more resources for promising configurations.
        },
        'parameters': {
            'learning_rate': {'distribution': 'log_uniform_values', 'min': 1e-4, 'max': 1e-3},
            'lora_r': {'values': [8, 16, 32]}, # Rank of the adapters
            'lora_alpha': {'values': [16, 32, 64]}, # Scaling factor
            'lora_dropout': {'values': [0.05, 0.1]} # Dropout for regularization
        }
    }
sweep_id = wandb.sweep(sweep_config, project="Voxtral-GLaDOS-Multimodal")
base_model = get_prepared_model(model_id, bnb_config, device, compute_dtype, processor)

def sweep_train_step():
    with wandb.init() as run:
        config = wandb.config
        output_dir = f"models/voxtral-sweep-{run.id}"
        sweep_train_set = train_dataset.select(range(800))
        sweep_eval_set = eval_dataset.shuffle(42).select(range(200))

        # Dynamic LoRA Config from Sweep
        lora_config = LoraConfig(
            r=config.lora_r,
            lora_alpha=config.lora_alpha,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            lora_dropout=config.lora_dropout,
            bias="none",
            task_type="CAUSAL_LM"
        )
        model = get_peft_model(base_model, lora_config)

        # Dynamic Training Args
        training_args = SFTConfig(
            output_dir=output_dir,
            num_train_epochs=1,
            per_device_train_batch_size=2,
            per_device_eval_batch_size=1,
            eval_strategy="steps",
            eval_steps=10,
            save_strategy="no",
            load_best_model_at_end=False,
            gradient_checkpointing=True,
            gradient_checkpointing_kwargs={"use_reentrant": False},
            gradient_accumulation_steps=8,
            dataloader_pin_memory=True,
            learning_rate=config.learning_rate,
            logging_steps=10,
            optim="paged_adamw_8bit",
            bf16=torch.cuda.is_bf16_supported(),
            fp16=not torch.cuda.is_bf16_supported(),
            remove_unused_columns=False,
            dataset_kwargs={"skip_prepare_dataset": True},
            report_to="wandb",
            loss_type="nll",
            use_liger_kernel=True,
            neftune_noise_alpha=5,
            lr_scheduler_type="cosine",
            warmup_ratio=0.03,
            weight_decay=0.01
        )
        # Initialize Trainer
        trainer = SFTTrainer(
            model=model,
            args=training_args,
            train_dataset=sweep_train_set,
            eval_dataset=sweep_eval_set,
            data_collator=make_voxtral_collate_fn(processor, compute_dtype),
            processing_class=processor
        )

        try:
            trainer.train()
        finally:
            model.unload()
            if 'trainer' in locals():
                trainer.optimizer = None
                trainer.lr_scheduler = None
                trainer.model = None
                trainer.train_dataset = None
                trainer.eval_dataset = None
                del trainer

            if 'model' in locals():
                del model

            gc.collect()
            gc.collect()
            torch.cuda.empty_cache()

print("Launching Weights & Biases Optimization Sweep...")
wandb.agent(sweep_id, function=sweep_train_step, count=5)

Create sweep with ID: 1u5xeuom
Sweep URL: https://wandb.ai/vitolus-universit-ca-foscari-venezia/Voxtral-GLaDOS-Multimodal/sweeps/1u5xeuom

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/762 [00:00<?, ?it/s]

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

Launching Weights & Biases Optimization Sweep...

wandb: Agent Starting Run: nprxyiqy with config:
wandb: 	learning_rate: 0.00012053529037253736
wandb: 	lora_alpha: 16
wandb: 	lora_dropout: 0.1
wandb: 	lora_r: 16
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
[transformers] Casting fp32 inputs back to torch.bfloat16 for flash-attn compatibility.
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:2982: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss, outputs = self.compute_loss(

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: qfgi6ged with config:
wandb: 	learning_rate: 0.0008116261497438576
wandb: 	lora_alpha: 64
wandb: 	lora_dropout: 0.05
wandb: 	lora_r: 32
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:2982: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss, outputs = self.compute_loss(

wandb: Agent Starting Run: tacio5yu with config:
wandb: 	learning_rate: 0.00020894051700661465
wandb: 	lora_alpha: 16
wandb: 	lora_dropout: 0.1
wandb: 	lora_r: 8
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:2982: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss, outputs = self.compute_loss(

wandb: Agent Starting Run: gjraaqap with config:
wandb: 	learning_rate: 0.0007526397580540165
wandb: 	lora_alpha: 16
wandb: 	lora_dropout: 0.05
wandb: 	lora_r: 8
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:2982: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss, outputs = self.compute_loss(

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: c1z9jvo4 with config:
wandb: 	learning_rate: 0.00013346819794411092
wandb: 	lora_alpha: 64
wandb: 	lora_dropout: 0.05
wandb: 	lora_r: 16
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /home/vito/.netrc.

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:2982: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss, outputs = self.compute_loss(

In [8]:
api = wandb.Api()
wandb_sweep = api.sweep(f"{api.default_entity}/Voxtral-GLaDOS-Multimodal/{sweep_id}")
best_params = wandb_sweep.best_run().config
del base_model, sweep_id, sweep_config
gc.collect()
torch.cuda.empty_cache()
with open("models/best_sweep_params.json", "w") as f:
    json.dump(best_params, f, indent=4)
print(f"Best Sweep Parameters: {best_params}")

wandb: Sorting runs by +summary_metrics.eval/loss

Best Sweep Parameters: {'bf16': True, 'fp16': False, 'fsdp': None, 'seed': 42, 'tf32': None, 'debug': [], 'dtype': 'bfloat16', 'optim': 'paged_adamw_8bit', 'lora_r': 8, 'do_eval': True, 'packing': False, 'project': 'huggingface', 'use_cpu': False, 'do_train': False, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'run_name': None, 'data_seed': None, 'deepspeed': None, 'eos_token': '<EOS_TOKEN>', 'hub_token': '<HUB_TOKEN>', 'log_level': 'passive', 'loss_type': 'nll', 'max_steps': -1, 'pad_token': '<PAD_TOKEN>', 'report_to': ['wandb'], 'use_cache': False, 'adam_beta1': 0.9, 'adam_beta2': 0.999, 'do_predict': False, 'eval_delay': 0, 'eval_steps': 10, 'local_rank': -1, 'lora_alpha': 16, 'max_length': 1024, 'model_type': 'voxtral', 'optim_args': None, 'output_dir': './models/voxtral-sweep-gjraaqap', 'save_steps': 500, 'vocab_size': 131072, 'ddp_backend': None, 'ddp_timeout': 1800, 'fsdp_config': None, 'hidden_size': 3072, 'label_names': None, 'logging_dir': None, 'peft_config': {'default': {'r': 8, 'bias': 'none', 'revision': None, 'use_dora': False, 'lora_bias': False, 'peft_type': 'LORA', 'task_type': 'CAUSAL_LM', 'eva_config': None, 'lora_alpha': 16, 'use_bdlora': None, 'use_qalora': False, 'use_rslora': False, 'arrow_config': None, 'auto_mapping': None, 'corda_config': None, 'lora_dropout': 0.05, 'peft_version': '0.19.1', 'megatron_core': 'megatron.core', 'fan_in_fan_out': False, 'inference_mode': False, 'layers_pattern': None, 'lora_ga_config': None, 'runtime_config': {'ephemeral_gpu_offload': False}, 'target_modules': ['q_proj', 'gate_proj', 'down_proj', 'k_proj', 'o_proj', 'up_proj', 'v_proj'], 'exclude_modules': None, 'megatron_config': None, 'modules_to_save': None, 'init_lora_weights': True, 'layer_replication': None, 'qalora_group_size': 16, 'target_parameters': None, 'ensure_weight_tying': False, 'layers_to_transform': None, 'alora_invocation_tokens': None, 'base_model_name_or_path': 'mistralai/Voxtral-Mini-3B-2507', 'trainable_token_indices': None}}, 'push_to_hub': False, 'return_dict': True, 'text_config': {'dtype': 'bfloat16', 'head_dim': 128, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'mlp_bias': False, 'use_cache': True, 'hidden_act': 'silu', 'model_type': 'llama', 'vocab_size': 131072, 'hidden_size': 3072, 'return_dict': True, 'bos_token_id': 1, 'eos_token_id': 2, 'pad_token_id': None, 'problem_type': None, 'rms_norm_eps': 1e-05, '_name_or_path': '', 'architectures': None, 'attention_bias': False, 'pretraining_tp': 1, 'sliding_window': None, 'rope_parameters': {'rope_type': 'default', 'rope_theta': 100000000}, 'attention_dropout': 0, 'initializer_range': 0.02, 'intermediate_size': 8192, 'num_hidden_layers': 30, 'output_attentions': False, 'is_encoder_decoder': False, 'num_attention_heads': 32, 'num_key_value_heads': 8, 'tie_word_embeddings': False, 'output_hidden_states': False, 'chunk_size_feed_forward': 0, 'max_position_embeddings': 131072}, 'adam_epsilon': 1e-08, 'audio_config': {'dtype': 'bfloat16', 'dropout': 0, 'head_dim': 64, 'id2label': {'0': 'LABEL_0', '1': 'LABEL_1'}, 'label2id': {'LABEL_0': 0, 'LABEL_1': 1}, 'layerdrop': 0, 'model_type': 'voxtral_encoder', 'vocab_size': 51866, 'hidden_size': 1280, 'return_dict': True, 'num_mel_bins': 128, 'problem_type': None, '_name_or_path': '', 'architectures': None, 'scale_embedding': False, 'attention_dropout': 0, 'initializer_range': 0.02, 'intermediate_size': 5120, 'num_hidden_layers': 32, 'output_attentions': False, 'activation_dropout': 0, 'is_encoder_decoder': False, 'activation_function': 'gelu', 'num_attention_heads': 20, 'num_key_value_heads': 20, 'max_source_positions': 1500, 'output_hidden_states': False, 'chunk_size_feed_forward': 0}, 'bos_token_id': 1, 'disable_tqdm': False, 'eos_token_id': 2, 'eval_packing': None, 'hub_model_id': None, 'hub_revision': None, 'hub_strategy': 'every_save', 'lora_dropout': 0.05, 'pad_token_id': 11, 'padding_free': False, 'problem_type': None, 'warmup_ratio': 0.03, 'warmup_steps': 0.03, 'weight_decay': 0.01, '_name_or_path': 'mistralai/Voxtral-Mini-3B-2507', 'architectures': ['VoxtralForConditionalGeneration'], 'eval_on_start': False, 'eval_strategy': 'steps', 'learning_rate': 0.0007526397580540165, 'logging_steps': 10, 'max_grad_norm': 1, 'save_strategy': 'no', 'torch_compile': False, 'audio_token_id': 24, 'bf16_full_eval': False, 'dataset_kwargs': {'skip_prepare_dataset': True}, 'fp16_full_eval': False, 'hub_always_push': False, 'save_only_model': False, 'shuffle_dataset': False, 'truncation_mode': 'keep_start', 'dataset_num_proc': None, 'ddp_static_graph': None, 'full_determinism': False, 'hub_private_repo': None, 'ignore_data_skip': False, 'log_on_each_node': True, 'logging_strategy': 'steps', 'num_train_epochs': 1, 'packing_strategy': 'bfd', 'save_total_limit': None, 'trackio_space_id': None, 'use_liger_kernel': True, 'ddp_bucket_cap_mb': None, 'greater_is_better': None, 'log_level_replica': 'warning', 'lr_scheduler_type': 'cosine', 'model_init_kwargs': None, 'output_attentions': False, 'save_on_each_node': False, 'trackio_bucket_id': None, 'trust_remote_code': False, 'accelerator_config': {'even_batches': True, 'non_blocking': False, 'split_batches': False, 'dispatch_batches': None, 'use_seedable_sampler': True, 'gradient_accumulation_kwargs': None}, 'batch_eval_metrics': False, 'chat_template_path': None, 'dataset_text_field': 'text', 'is_encoder_decoder': False, 'length_column_name': 'length', 'logging_first_step': False, 'pad_to_multiple_of': None, 'parallelism_config': None, 'torch_compile_mode': None, 'assistant_only_loss': False, 'include_for_metrics': [], 'liger_kernel_config': None, 'lr_scheduler_kwargs': None, 'neftune_noise_alpha': 5, 'quantization_config': {'load_in_4bit': True, 'load_in_8bit': False, 'quant_method': 'BITS_AND_BYTES', '_load_in_4bit': True, '_load_in_8bit': False, 'llm_int8_threshold': 6, 'bnb_4bit_quant_type': 'nf4', 'llm_int8_skip_modules': None, 'bnb_4bit_compute_dtype': 'bfloat16', 'bnb_4bit_quant_storage': 'uint8', 'llm_int8_has_fp16_weight': False, 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False}, 'skip_memory_metrics': True, 'auto_find_batch_size': False, 'completion_only_loss': None, 'dataloader_drop_last': False, 'model/num_parameters': 4691753984, 'optim_target_modules': None, 'output_hidden_states': False, 'prediction_loss_only': False, 'projector_hidden_act': 'gelu', 'router_aux_loss_coef': 0.001, 'transformers_version': '5.12.1', 'activation_offloading': False, 'dataloader_pin_memory': True, 'ddp_broadcast_buffers': None, 'enable_jit_checkpoint': False, 'metric_for_best_model': None, 'remove_unused_columns': False, 'torch_compile_backend': None, 'dataloader_num_workers': 0, 'eval_do_concat_batches': True, 'eval_use_gather_object': False, 'gradient_checkpointing': True, 'label_smoothing_factor': 0, 'load_best_model_at_end': False, 'logging_nan_inf_filter': True, 'resume_from_checkpoint': None, 'chunk_size_feed_forward': 0, 'eval_accumulation_steps': None, 'torch_empty_cache_steps': None, 'trackio_static_space_id': None, 'train_sampling_strategy': 'random', 'dataloader_prefetch_factor': None, 'ddp_find_unused_parameters': None, 'per_device_eval_batch_size': 1, 'gradient_accumulation_steps': 8, 'per_device_train_batch_size': 2, 'average_tokens_across_devices': True, 'dataloader_persistent_workers': False, 'gradient_checkpointing_kwargs': {'use_reentrant': False}, 'include_num_input_tokens_seen': 'no', 'restore_callback_states_from_checkpoint': False}

#### Supervised Fine-Tuning with TRL's SFTTrainer

In [4]:
best_params = {
    'learning_rate': 3e-4,
    'lora_r': 16,
    'lora_alpha': 32,
    'lora_dropout': 0.1
    }
if os.path.exists("models/best_sweep_params.json"):
    with open("models/best_sweep_params.json", "r") as f:
        best_params = json.load(f)
output_dir = "models/voxtral-glados-sft"
last_checkpoint = get_last_checkpoint(output_dir) if os.path.exists(output_dir) else None

print(f"Loading {model_id} for final production run...")
model = get_prepared_model(model_id, bnb_config, device, compute_dtype, processor)

lora_config = LoraConfig(
    r=best_params['lora_r'],
    lora_alpha=best_params['lora_alpha'],
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=best_params['lora_dropout'],
    bias="none",
    task_type="CAUSAL_LM"
)

training_args = SFTConfig(
    output_dir=output_dir,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=1,
    eval_strategy="steps",
    eval_steps=500,
    save_strategy="steps",
    save_steps=500,
    save_total_limit=3,
    load_best_model_at_end=False,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    gradient_accumulation_steps=8,
    dataloader_num_workers=4,
    dataloader_pin_memory=True,
    dataloader_prefetch_factor=2,
    learning_rate=best_params['learning_rate'],
    logging_steps=10,
    num_train_epochs=3,
    optim="paged_adamw_8bit", # paged_adamw_8bit use ram if vram is saturated (paging)
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported(),
    remove_unused_columns=False, # Crucial so the collator receives the dicts
    dataset_kwargs={"skip_prepare_dataset": True},
    report_to="wandb",
    loss_type="nll",
    use_liger_kernel=True,
    neftune_noise_alpha=5, # Add a small amount of noise to the activations during training to improve generalization
    lr_scheduler_type="cosine",
    warmup_ratio=0.03,
    weight_decay=0.01
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=make_voxtral_collate_fn(processor, compute_dtype),
    processing_class=processor,
    peft_config=lora_config
)
trainer.model.print_trainable_parameters()

Loading mistralai/Voxtral-Mini-3B-2507 for final production run...

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/762 [00:00<?, ?it/s]

/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 15,482,880 || all params: 4,691,753,984 || trainable%: 0.3300

In [ ]:
try:
    if last_checkpoint:
        print(f"Resuming training from {last_checkpoint}...")
        trainer.train(resume_from_checkpoint=last_checkpoint)
    else:
        print("Starting a new training run...")
        trainer.train()
    # Save the final adapter weights
    trainer.save_model(os.path.join(output_dir, "final_adapters"))
    print("Training complete. Adapters saved.")
finally:
    del model, trainer
    gc.collect()
    torch.cuda.empty_cache()
    wandb.finish()

Starting a new training run...

[transformers] Casting fp32 inputs back to torch.bfloat16 for flash-attn compatibility.
/home/vito/miniconda3/envs/pyqwen/lib/python3.12/site-packages/transformers/trainer.py:1915: UserWarning: liger-kernel did not return token_accuracy when requested. The mean_token_accuracy metric will not be logged. This is unexpected; please report it to the liger-kernel repository.
  loss = self.compute_loss(model, inputs, num_items_in_batch=num_items_in_batch)